### get all current memberships
GET http://localhost:3000/api/currentmemberships/

### get one current membership
GET http://localhost:3000/api/currentmemberships/66881354094fb79b203582e0

### create current membership
POST http://localhost:3000/api/currentmemberships/
Content-Type: application/json

{
  "type": "66880b57ce8ccd39d9fe9085",
  "client": "666c45e6b7de20e525df8d1e"
}


### put current membership
PUT http://localhost:3000/api/currentmemberships/66881354094fb79b203582e0
Content-Type: application/json

{
  "type": "66880b57ce8ccd39d9fe9085",
  "client": "666c45e6b7de20e525df8d1e"
}


### patch current membership
PATCH http://localhost:3000/api/currentmemberships/668817edd51fc4600353eaf6
Content-Type: application/json

{
    "client": "667ad97c462b348eed0715ed"
}


### delete current membership
DELETE http://localhost:3000/api/currentmemberships/6688149f1248ffd919ac105d