### get all clients with an active membership
GET http://localhost:3000/api/memberships/active/


### create routine
POST http://localhost:3000/api/routines/
Content-Type: application/json

{
  "trainer": "66e49c22a6f2eda0d551a86a",
  "client": "66f2c90e40cbb8cdc6beebf4",
  "start": "2141-02-28T03:00:00.000Z",
  "end": "2141-02-30T03:00:00.000Z",
  "exercisesRoutine":
  [
    {
      "week": 1,
      "day": 1,
      "series": 1,
      "repetitions": 10,
      "weight": 100,
      "exercise": "66f45a01bfd7acd78c8663ea"
    },
    {
      "week": 1,
      "day": 1,
      "series": 4,
      "repetitions": 8,
      "weight": 0,
      "exercise": "66f43dab73be6c67c26cbe89"
    }
  ]
}