### get all Class Types
GET http://localhost:3000/api/classes/types

### get one class type
GET http://localhost:3000/api/classes/types/668f2966d26bd5198daac425


### create class type
POST http://localhost:3000/api/classes/types/
Content-Type: application/json

{
  "name": "Pilates", 
  "description": "permite trabajar los músculos en profundidad mientras los relaja, gracias al trabajo de la respiración"
}

### put class type
PUT http://localhost:3000/api/classes/types/668f2966d26bd5198daac425
Content-Type: application/json

{
  "name": "Zumba", 
  "description": "es baile"
}

### patch class type (parcial)
PATCH http://localhost:3000/api/classes/types/668f2966d26bd5198daac425
Content-Type: application/json

{
  "description": "es baile fitness"
}

### delete class type
DELETE http://localhost:3000/api/classes/types/668f2966d26bd5198daac425
