### get all registrations
GET http://localhost:3000/api/registrations

### get one registration
GET http://localhost:3000/api/registrations/66c3e3535f6f028235485e3b

### post one registration
POST http://localhost:3000/api/registrations/
Content-Type: application/json

{
  "client": "66c3c81bcacb77c1b26afe9d", 
  "class": "66c3c85ecacb77c1b26afea0"
}

### update one registration
PUT http://localhost:3000/api/registrations/66c3e112e12ac3e83ceee86c
Content-Type: application/json

{
  "client": "66c3c81bcacb77c1b26afe9d", 
  "class": "66c3d93e1393c6b1791f1a8c"
}

### update(parcial) one registration
PATCH http://localhost:3000/api/registrations/66c3e112e12ac3e83ceee86c
Content-Type: application/json

{
  "class": "66c3c85ecacb77c1b26afea0"
}

### delete one registration
DELETE http://localhost:3000/api/registrations/66c3e3535f6f028235485e3b