@token = insertar_token

### get all registrations
GET http://localhost:3000/api/classes/registration
Cookie: auth_token={{token}}


### get one registration
GET http://localhost:3000/api/classes/registration/66c3e3535f6f028235485e3b
Cookie: auth_token={{token}}


### get registrations by client
GET http://localhost:3000/api/classes/registration/client/66f2fb46c89589b79fe56c13
Cookie: auth_token={{token}}


### register for a class
POST http://localhost:3000/api/classes/registration/
Cookie: auth_token={{token}}
Content-Type: application/json

{
  "client": "66c3c81bcacb77c1b26afe9d", 
  "class": "66c3c85ecacb77c1b26afea0"
}


### cancel a registration
PATCH http://localhost:3000/api/classes/registration/cancel/66c3e112e12ac3e83ceee86c
Cookie: auth_token={{token}}
