### login client
POST http://localhost:3000/api/auth/
Content-Type: application/json

{
  "email": "claudia@reynares.com.ar",
  "password": "claudia"
}


### login trainer
POST http://localhost:3000/api/auth/
Content-Type: application/json

{
  "email": "aaron@debernardo.com",
  "password": "aaron"
}


### login wrong
POST http://localhost:3000/api/auth/
Content-Type: application/json

{
  "email": "hernantarabella@hotmail.com.ar",
}

### logout
POST http://localhost:3000/api/auth/logout/
Cookie: auth_token=insertar_token
