### get all ClassList
GET http://localhost:3000/api/classLists

### get one classList
GET http://localhost:3000/api/classLists/id


### create classList
POST http://localhost:3000/api/classLists/
Content-Type: application/json

{
  "classHour" : "8:00PM",
  "classDay": "Tuesday",
  "state": "active",
  "classDuration": 60,
  "maxCapacity": 20,
  "place": "gym",
  "classType": "668f29b1d26bd5198daac426",
  "trainer": "667ecacbb3067b3bacc87c8e"
}

### put classList
PUT http://localhost:3000/api/classLists/668f2cc8513f00900b178594
Content-Type: application/json

{
  "classHour" : "8:00PM",
  "classDay": "Tuesday",
  "state": "disable",
  "classDuration": 30,
  "maxCapacity": 10,
  "place": "sum",
  "classType": "668f29b1d26bd5198daac426",
  "trainer": "667ecacbb3067b3bacc87c8e"
}

### patch classList (parcial)
PATCH http://localhost:3000/api/classLists/668f2cc8513f00900b178594
Content-Type: application/json

{

  "state": "disable",

}


### delete classList
DELETE http://localhost:3000/api/classLists/668f2cc8513f00900b178594
