### get all clients
GET http://localhost:3000/api/clients


### get one client
GET http://localhost:3000/api/clients/666cd30a68b1b03168a170a

### create client
POST http://localhost:3000/api/clients/
Content-Type: application/json

{
  "username": "Milton",
  "password": "mil123",
  "email": "borsatomilton@gmail.com",
  "firstName": "Milton Rubén",
  "lastName": "BorsatoGiménez"
}


### put client
PUT http://localhost:3000/api/clients/666cc6e2280240a5542a472a
Content-Type: application/json

{
  "username": "Salvador",
  "password": "salvi1234",
  "email": "notiene@gmail.com",
  "firstName": "Carlos Salvador",
  "lastName": "Bilardo"
}


### patch client
PATCH http://localhost:3000/api/clients/666ccf0da12840b4bdc20261
Content-Type: application/json

{
  "firstName": "Mariana"
}


### delete client
DELETE http://localhost:3000/api/clients/666cd63d8b5604d0d0c1f199