### get all clients
GET http://localhost:3000/api/clients

### get one client
GET http://localhost:3000/api/clients/666dd5dae54ba86485903105

### create client
POST http://localhost:3000/api/clients/
Content-Type: application/json

{
  "username": "gasti1234",
  "password": "******",
  "email": "gasti@hotmail.com.ar",
  "firstName": "Gastón",
  "lastName": "Hernández"
}


### put client
PUT http://localhost:3000/api/clients/666cc6e2280240a5542a472a
Content-Type: application/json

{
  "username": "Salvador",
  "password": "salvi1234",
  "email": "notiene@gmail.com",
  "firstName": "Carlos Salvador",
  "lastName": "Bilardo"
}


### patch client
PATCH http://localhost:3000/api/clients/666dd5dae54ba86485903105
Content-Type: application/json

{
  "firstName": "Alejo"
}


### delete client
DELETE http://localhost:3000/api/clients/666cca4599dc046e1bdc7a4e