@token = insertar_token

### get all
GET http://localhost:3000/api/clients/goals
Cookie: auth_token={{token}}


### get one
GET http://localhost:3000/api/clients/goals/667ad85f462b348eed0715eb
Cookie: auth_token={{token}}

### get by user id
GET http://localhost:3000/api/clients/goals/user-id/66f2fb46c89589b79fe56c13
Cookie: auth_token={{token}}

### añadir uno
POST  http://localhost:3000/api/clients/goals/
Cookie: auth_token={{token}}
Content-Type: application/json

{
  "fatPercentage": "8",
  "bodyMeasurements": "",
  "client": "667f4692dd0e068972898abc"
}


### modificación total
PUT http://localhost:3000/api/clients/goals/667ad85f462b348eed0715eb
Cookie: auth_token={{token}}
Content-Type: application/json

{
  "fatPercentage": "22",
  "bodyMeasurements": "",
  "client": "667f4692dd0e068972898abc"
}


### modificación parcial
PATCH http://localhost:3000/api/clients/goals/667ad85f462b348eed0715eb
Cookie: auth_token={{token}}
Content-Type: application/json

{
  "done": true
}


### borrar una meta
DELETE http://localhost:3000/api/clients/goals/667f48579899199c6a75c763
Cookie: auth_token={{token}}
