### get all
GET http://localhost:3000/api/goal/

### get one
GET http://localhost:3000/api/goal/667f48579899199c6a75c763

### añadir uno
POST  http://localhost:3000/api/goal/
Content-Type: application/json

{
  "fatPercentage": "8",
  "bodyMeasurements": "",
  "client": "667f4692dd0e068972898abc"
}

### modificación parcial
PATCH http://localhost:3000/api/goal/667f48579899199c6a75c763
Content-Type: application/json

{
  "fatPercentage": "123"
}

### modificación parcial
PATCH http://localhost:3000/api/goal/666dde787e10844d9ae57049
Content-Type: application/json

{
  "done": true
}

### borrar una meta
DELETE http://localhost:3000/api/goal/667f48579899199c6a75c763